name: "LeRobert - no addBlock" 
author: "Clara"
description: Measuring Le Robert - no add blocker
version: 1

services:
  browser-client:
    image: prueba-leRobert
    build:
      context: .
    command: sleep infinity

flow:
  - name: SearchWords
    container: browser-client
    commands:
      - type: console
        command: python measure_leRobert_noAddBlock.py
        note: "serching for words"
