name: "YouTube Free" # Cambia esto a "YouTube AdBlock" o "YouTube Premium" según corresponda
author: "Arturo"
description: Measuring youtube free version
version: 1

services:
  browser-client:
    image: prueba-youtube

flow:
  - name: PlayVideo
    container: browser-client
    commands:
      - type: console
        command: python measure.py
        note: "Reproduciendo video de YouTube"
